### PR TITLE
    added pandas process

### PR DESCRIPTION
**Pull request by cehbrecht**
## Overview

This PR adds an example process for pandas and with a CSV complex input.

Changes:

* Added tests with input "penguins.csv" as reference and embedded.

### CODE REVIEW

**Comment by Zeitsperre** [comment]
Looks good to me. What do you think of extending Birdy to return opened CSV objects as `pandas.Datasets`?

**Review by Zeitsperre — APPROVED** [review]

**Comment by cehbrecht** [comment]
> Looks good to me. What do you think of extending Birdy to return opened CSV objects as `pandas.Datasets`?

Would you like to open an issue for this on birdy? I suppose it depends how oft this will be used. Currently I'm getting more involved in using intake and pandas ...

**Comment by cehbrecht** [comment]
@Zeitsperre thanks for review :)

**Comment by nikola-rados** [comment]
Thank you for this @cehbrecht! We were missing a couple of small details in our bird.

**Pull request merged**
