### PR TITLE
Set as_reference to False for some ComplexOutput 

### PR DESCRIPTION
**Pull request by huard**
## Overview

Allows to exercise raw data in response.

### CODE REVIEW

**Comment by cehbrecht** [comment]
@huard 
fixed pep8.

Don't understand why I get an assert error:
```
Traceback (most recent call last):
  File "/Users/pingu/Documents/GitHub/birdhouse/emu/tests/test_wps_inout.py", line 21, in test_wps_inout
    assert out['text'] == 'some string'
AssertionError: assert 'http://local...8a2/input.txt' == 'some string'
  - http://localhost:5000/outputs/0ad2d2a4-fec2-11e8-af08-685b35a278a2/input.txt
  + some string
```

When run manually, a CDATA is returned:

http://localhost:5000/wps?version=1.0.0&service=wps&request=Execute&identifier=inout

```
<wps:Output>
      <ows:Identifier>text</ows:Identifier>
      <ows:Title>Text</ows:Title>
      <ows:Abstract>Copy of input text file.</ows:Abstract>
      <wps:Data>
        <wps:ComplexData mimeType="text/plain" encoding="" schema="">
          <![CDATA[
                            request didn&#39;t have a text file.
                    ]]>
        </wps:ComplexData>
      </wps:Data>
    </wps:Output>
```

**Comment by cehbrecht** [comment]
Ok, this changes the picture:

http://localhost:5000/wps?version=1.0.0&service=wps&request=Execute&identifier=inout&DataInputs=text=some-string

```
<wps:Output>
      <ows:Identifier>text</ows:Identifier>
      <ows:Title>Text</ows:Title>
      <ows:Abstract>Copy of input text file.</ows:Abstract>
      <wps:Reference href="http://localhost:5000/outputs/cb044238-fec2-11e8-8c76-685b35a278a2/input.txt" mimeType="text/plain" encoding="" schema="" />
    </wps:Output>
```

Looks like an issue in pywps ...

**Comment by huard** [comment]
See https://github.com/lazaa32/pywps/pull/1

**Comment by cehbrecht** [comment]
this works with pywps PR: 
https://github.com/geopython/pywps/pull/431

**Pull request merged**
