### PR TITLE
Added process with non-standard identifiers

### LINKED ISSUE #77: Add process with non-python identifier
## Description

Add a dummy process whose identifier contains characters that are not allowed in python variables. 
Would be useful to test owslib and birdy.

### PR DESCRIPTION
**Pull request by huard**
## Overview

This PR fixes #77 

Changes:

* Added process with identifiers including spaces, -, .

### CODE REVIEW

**Comment by huard** [comment]
@cehbrecht Are there other characters that we should include ?

@davidcaron Proposing this new process to check that birdy works as expected with non-pythonic identifiers.

**Comment by huard** [comment]
See http://www.datypic.com/sc/xsd/t-xsd_string.html for info on what is allowed.

**Comment by huard** [comment]
I added other allowed characters (&;é) and it broke...

**Comment by cehbrecht** [comment]
@huard You have raised the level quite high ... pywps is also breaking. Can we start simpler (fixing birdy, owslib) and go further when necessary?

The following process identifier works:
```
fake.process_for-testing
```

At least it has a `.` and a `-` ... I have forgotten the original issue in birdy ...

**Pull request merged**
